<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>preview</LangVersion>
    <Description>Versioned XBF decompilation support for MrmTool.</Description>
  </PropertyGroup>

  <ItemGroup>
    <None Update="V2\License.txt" Pack="true" PackagePath="" />
  </ItemGroup>

</Project>
